name: flutter_gutenberg_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  font_awesome_flutter: ^10.1.0
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  equatable: ^2.0.3
  envied: ^0.5.4+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  bloc: ^8.1.4
  flutter_snake_navigationbar: ^0.6.1
  mocktail: ^1.0.4
  flutter_secure_storage: ^4.2.1
  shared_preferences: ^2.2.3
  http: ^1.2.1
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  bloc_test: ^9.1.7
  path_provider: ^2.1.3
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/status_images/
